
version: 2
updates:

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    assignees:
      - IncPlusPlus
    target-branch: main

  # Maintain dependencies for nuget
  - package-ecosystem: nuget
    directory: /
    schedule: 
      interval: daily
    open-pull-requests-limit: 10
    assignees:
      - IncPlusPlus
    target-branch: main
