- color: 7121c6
  description: Pull requests that update .net code
  name: .NET
- color: d73a4a
  description: Something isn't working
  name: bug
- color: ededed
  description: General repository maintenance work
  name: chore
- color: 0366d6
  description: Pull requests that update a dependency file
  name: dependencies
- color: 0075ca
  description: Improvements or additions to documentation
  name: documentation
- color: cfd3d7
  description: This issue or pull request already exists
  name: duplicate
- color: a2eeef
  description: New feature or request
  name: enhancement
- color: 00fcff
  description: ""
  name: feature
- color: 7057ff
  description: Good for newcomers
  name: good first issue
- color: "008672"
  description: Extra attention is needed
  name: help wanted
- color: e4e669
  description: This doesn't seem right
  name: invalid
- color: 3DC634
  description: This is a large change that should change the major version
  name: major
- color: 0038CF
  description: A considerable change that should increment the minor version
  name: minor
- color: fbca04
  description: A small change that should only increment the patch version
  name: patch
- color: d876e3
  description: Further information is requested
  name: question
- color: ffffff
  description: This will not be worked on
  name: wontfix
- color: ededed
  description: ""
  name: "\U0001F6E0 Improvement"