name: Build
on: 
  push:
  pull_request:
    types: [synchronize, opened]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Show dotnet info 
        run: dotnet --info

      - name: Add dotnet-format problem matcher
        uses: xt0rted/dotnet-format-problem-matcher@v1

      - name: Restore dotnet tools
        uses: xt0rted/dotnet-tool-restore@v1

      - name: Run dotnet format
        run: dotnet format --check
# https://github.com/xt0rted/dotnet-format/issues/174
#      - name: Run dotnet format
#        uses: xt0rted/dotnet-format@v1

      # Without this, the project will fail to build because ZipExtractor won't be present in the Resources dir
      - name: Create a single-file executable of ZipExtractor
        run: dotnet publish ZipExtractor

      - name: Attempt to build project
        run: dotnet build

      - name: Show exe version info
        run: dotnet versioninfo Windows/bin/Debug/net5.0-windows/win10-x64/titanfall2-rp.exe -j

      - name: Show dll version info
        run: dotnet versioninfo Windows/bin/Debug/net5.0-windows/win10-x64/titanfall2-rp.dll -j

      - name: Show wine exe version info
        run: dotnet versioninfo Wine/bin/Debug/net5.0/win10-x64/titanfall2-rp-Wine.exe -j

      - name: Show wine dll version info
        run: dotnet versioninfo Wine/bin/Debug/net5.0/win10-x64/titanfall2-rp-Wine.dll -j
