name: Build
on: [push]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Show dotnet info 
        run: dotnet --info

      - name: Add dotnet-format problem matcher
        uses: xt0rted/dotnet-format-problem-matcher@v1

      - name: Restore dotnet tools
        uses: xt0rted/dotnet-tool-restore@v1
      
      - name: Run dotnet format
        run: dotnet format --check
# https://github.com/xt0rted/dotnet-format/issues/174
#      - name: Run dotnet format
#        uses: xt0rted/dotnet-format@v1

      - name: Attempt to build project
        run: dotnet build
          
      - name: Show exe version info
        run: dotnet versioninfo titanfall2-rp/bin/Debug/net5.0/win10-x64/titanfall2-rp.exe -j
          
      - name: Show dll version info
        run: dotnet versioninfo titanfall2-rp/bin/Debug/net5.0/win10-x64/titanfall2-rp.dll -j

      - name: Put the exe version in a step output
        run: echo "::set-output name=version::$(dotnet versioninfo titanfall2-rp/bin/Debug/net5.0/win10-x64/publish/titanfall2-rp.exe -j | jq .[0])"
        id: version-grab-step
        
      - name: Grab the stored version
        run: echo "The stored version was ${{ steps.version-grab-step.outputs.version }}"