name: Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Add dotnet-format problem matcher
        uses: xt0rted/dotnet-format-problem-matcher@v1

      - name: Restore dotnet tools
        uses: xt0rted/dotnet-tool-restore@v1
      
      - name: Run dotnet format
        run: dotnet format --check
# https://github.com/xt0rted/dotnet-format/issues/174
#      - name: Run dotnet format
#        uses: xt0rted/dotnet-format@v1

      - name: Set up .NET Core SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'
        
      - name: Attempt to build project
        run: dotnet build
        